/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#061b0e',
        'on-primary': '#ffffff',
        'primary-container': '#1b3022',
        'on-primary-container': '#819986',
        'inverse-primary': '#b4cdb8',
        'primary-fixed': '#d0e9d4',
        'primary-fixed-dim': '#b4cdb8',
        'on-primary-fixed': '#0b2013',
        'on-primary-fixed-variant': '#364c3c',
        'secondary': '#536346',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6e9c3',
        'on-secondary-container': '#59694b',
        'secondary-fixed': '#d6e9c3',
        'secondary-fixed-dim': '#bacca8',
        'on-secondary-fixed': '#111f08',
        'on-secondary-fixed-variant': '#3c4b30',
        'tertiary': '#1f1509',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#35291c',
        'on-tertiary-container': '#a18f7e',
        'tertiary-fixed': '#f4dfcb',
        'tertiary-fixed-dim': '#d7c3b0',
        'on-tertiary-fixed': '#241a0e',
        'on-tertiary-fixed-variant': '#524436',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-bright': '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#434843',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        'outline': '#737973',
        'outline-variant': '#c3c8c1',
        'surface-tint': '#4d6453',
        'surface-variant': '#e4e2dd',
        'background': '#fbf9f4',
        'on-background': '#1b1c19',
      },
      fontFamily: {
        'caslon': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'manrope': ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['3rem', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg-mobile': ['2.25rem', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['2rem', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-sm': ['1.5rem', { lineHeight: '1.4', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['0.875rem', { lineHeight: '1.5', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-gap': '120px',
        'gutter': '24px',
      },
      maxWidth: {
        'container': '1280px',
      },
      boxShadow: {
        'botanical': '0 20px 60px rgba(27, 48, 34, 0.08)',
        'botanical-sm': '0 8px 30px rgba(27, 48, 34, 0.06)',
        'botanical-lg': '0 40px 80px rgba(27, 48, 34, 0.12)',
      },
    },
  },
  plugins: [],
};
