import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);
export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('vl_lang') || 'en');
  const isAr = lang === 'ar';

  useEffect(() => {
    localStorage.setItem('vl_lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = isAr ? 'rtl' : 'ltr';
    document.body.classList.toggle('font-arabic', isAr);
  }, [lang, isAr]);

  const toggle = () => setLang(l => (l === 'en' ? 'ar' : 'en'));
  const t = (key) => {
    const val = TRANSLATIONS[lang]?.[key];
    if (val === undefined) return TRANSLATIONS['en'][key] ?? key;
    return val;
  };

  return (
    <LanguageContext.Provider value={{ lang, isAr, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const TRANSLATIONS = {
  en: {
    brand: 'Nabta', tagline: 'BOTANICAL RESEARCH INSTITUTE',
    nav_discover: 'Discover', nav_categories: 'Categories', nav_journal: 'Journal',
    nav_about: 'About', nav_consult: 'Consult Expert', nav_switchLang: 'AR',
    home_hero_title: "Nature's Wisdom,\nScientifically Refined.",
    home_hero_sub: 'Explore the intersection of traditional herbalism and modern clinical research. Elevate your wellness through curated, evidence-based botanical education.',
    home_cta_explore: 'Explore Compendium', home_cta_journal: 'Read Latest Journal',
    home_sleep_title: 'Sleep & Calm', home_sleep_desc: 'Botanical allies to quiet the mind, ease tension, and promote restorative rest. Discover tinctures and teas featuring Valerian, Chamomile, and Ashwagandha.',
    home_immunity_title: 'Immunity', home_immunity_desc: 'Fortify your natural defenses with potent extracts of Echinacea, Elderberry, and medicinal mushrooms.',
    home_vitality_title: 'Vitality', home_vitality_desc: 'Awaken natural energy reserves and support endurance. A curated selection of stimulating herbs including Ginseng, Rhodiola, and Eleuthero.',
    home_digestion_title: 'Digestion', home_digestion_desc: 'Soothe and optimize the digestive system with bitter tonics and carminatives like Ginger and Peppermint.',
    home_potm_badge: 'Plant of the Month', home_potm_latin: 'Echinacea purpurea',
    home_potm_desc: 'Renowned for its immunomodulatory properties, Echinacea stands at the forefront of natural prophylactic research. Our latest systematic review examines its...',
    home_view_profile: 'View Full Profile', home_explore: 'Explore Collection',
    cats_title: 'Apothecary Collections',
    cats_sub: "Explore our curated categories of botanical preparations, designed to support specific facets of your well-being. Each collection draws upon scientific authority and traditional organic elegance.",
    cats_explore: 'Explore Collection',
    cat_immunity_name: 'Immunity', cat_immunity_tagline: 'Fortify your natural defenses with potent extracts of Echinacea, Elderberry, and medicinal mushrooms.',
    cat_immunity_long: "Discover nature's powerful defenders. This curated selection of medicinal plants has been traditionally utilized to fortify the body's natural defenses, offering a holistic approach to maintaining wellness and vitality throughout the changing seasons.",
    cat_digestive_name: 'Digestive Health', cat_digestive_tagline: 'Soothe and optimize the digestive system with bitter tonics and carminatives like Ginger and Peppermint.',
    cat_digestive_long: 'Support your digestive wellness with time-tested herbal preparations. From bitter tonics that stimulate digestive enzymes to carminatives that ease discomfort, these plants support every aspect of healthy digestion and nutrient absorption.',
    cat_respiratory_name: 'Respiratory Health', cat_respiratory_tagline: 'Support clear airways and healthy breathing with time-tested botanical preparations.',
    cat_respiratory_long: 'Breathe easier with botanical support for your respiratory system. These time-honored herbs help maintain clear airways, soothe irritated mucous membranes, and support overall lung health through seasonal challenges.',
    cat_womens_name: "Women's Health", cat_womens_tagline: 'Support hormonal balance, cycles, and vitality with carefully curated botanical allies.',
    cat_womens_long: "A thoughtful collection of plants that have supported women's health across cultures and centuries. These botanicals address hormonal balance, menstrual comfort, and the transitions of a woman's life with gentle, plant-based wisdom.",
    plant_view_profile: 'View Profile', plant_save: 'Save plant',
    plant_save_journal: 'Save to Journal', plant_history: 'History & Origin',
    plant_benefits: 'Scientific Benefits',
    plant_pharmacology_intro: 'Modern pharmacology has begun to validate what traditional healers have known for millennia. The primary active compounds are responsible for its documented therapeutic effects.',
    plant_preparation: 'Preparation Methods', plant_symptoms: 'Associated Symptoms',
    plant_related: 'Related Plants', plant_botanical_facts: 'Botanical Facts',
    plant_family: 'Family', plant_native: 'Native Region', plant_growth: 'Growth Habit',
    plant_compounds: 'Active Compounds', plant_cultivation: 'Cultivation Notes',
    plant_part_of: 'Part of Collection', plant_best_for: 'BEST FOR',
    q_title: 'Community Wellness Insights', q_sub: 'Aggregated data from questionnaire responses — updated in real time.',
    q_chart_symptoms: 'Most Reported Symptoms', q_chart_symptoms_sub: 'Total community responses',
    q_chart_categories: 'Category Interest', q_chart_categories_sub: 'Distribution of user focus areas',
    q_chart_trends: 'Wellness Engagement Trends', q_chart_trends_sub: 'Monthly growth in users & plant profiles explored',
    q_tab_questionnaire: 'Questionnaire', q_tab_results: 'My Results',
    q_step_of: 'Step', q_of: 'of', q_complete: 'complete',
    q_back: 'Back', q_continue: 'Continue', q_finish: 'Get My Recommendations',
    q_start: 'Start Questionnaire →', q_no_results: 'Complete the questionnaire to see your results.',
    q_users: 'Active Users', q_plants_explored: 'Plants Explored',
    qq1_q: 'What is your primary health concern?', qq1_sub: 'Select the area that matters most to you right now.',
    qq2_q: 'Which symptoms are you currently experiencing?', qq2_sub: 'Select all that apply.',
    qq3_q: 'How would you describe your current lifestyle?', qq3_sub: 'This helps us tailor recommendations to your situation.',
    qq4_q: 'What is your experience with herbal medicine?', qq4_sub: "We'll match recommendations to your comfort level.",
    qq5_q: 'What is your primary wellness goal?', qq5_sub: 'Select the outcome most important to you.',
    opt_immunity: 'Immune Support', opt_immunity_desc: 'Strengthening defenses',
    opt_digestive: 'Digestive Health', opt_digestive_desc: 'Gut comfort & function',
    opt_respiratory: 'Respiratory Health', opt_respiratory_desc: 'Breathing & airways',
    opt_womens: "Women's Wellness", opt_womens_desc: 'Hormonal & cycle health',
    opt_stress: 'Stress & Energy', opt_stress_desc: 'Mental & physical vitality',
    opt_sleep: 'Sleep Quality', opt_sleep_desc: 'Rest & recovery',
    opt_fatigue: 'Fatigue', opt_anxiety: 'Anxiety / Stress', opt_poor_sleep: 'Poor Sleep',
    opt_digestive_issues: 'Digestive Issues', opt_ibs: 'IBS / Bloating', opt_cough: 'Cough / Cold',
    opt_low_immunity: 'Low Immunity', opt_hormonal: 'Hormonal Imbalance',
    opt_sedentary: 'Mostly Sedentary', opt_sedentary_desc: 'Desk-based, minimal exercise',
    opt_moderate: 'Moderately Active', opt_moderate_desc: 'Light exercise 2-3x/week',
    opt_active: 'Very Active', opt_active_desc: 'Regular intense exercise',
    opt_high_stress: 'High Stress', opt_high_stress_desc: 'Demanding work/life demands',
    opt_beginner: 'Complete Beginner', opt_beginner_desc: 'New to herbal wellness',
    opt_some: 'Some Experience', opt_some_desc: 'Used teas or supplements',
    opt_experienced: 'Experienced', opt_experienced_desc: 'Familiar with tinctures, herbs',
    opt_prevention: 'Prevention', opt_prevention_desc: 'Maintain and protect health',
    opt_acute: 'Address Acute Issues', opt_acute_desc: 'Resolve current symptoms',
    opt_longterm: 'Long-term Vitality', opt_longterm_desc: 'Build lasting wellness',
    opt_education: 'Learn & Explore', opt_education_desc: 'Understand botanical medicine',
    res_title: 'Your Botanical Profile', res_sub: 'Based on your responses, here are your personalized botanical recommendations.',
    res_focus: 'Focus Area', res_symptoms: 'Key Symptoms', res_recommended: 'Recommended Plants for You',
    res_explore_all: 'Explore All Categories', res_retake: 'Retake Questionnaire',
    res_disclaimer: '⚠️ These recommendations are for educational purposes only. Always consult a qualified healthcare provider.',
    about_title: 'About Nabta', about_sub: 'Nabta is a botanical research institute dedicated to bridging the gap between traditional herbal wisdom and modern clinical science.',
    about_evidence: 'Evidence-Based', about_evidence_desc: 'Every plant profile is grounded in peer-reviewed research and traditional clinical use.',
    about_sourced: 'Ethically Sourced', about_sourced_desc: 'We partner with responsible growers who practice sustainable, regenerative agriculture.',
    about_education: 'Botanical Education', about_education_desc: 'Our goal is empowerment through knowledge — not replacement of medical care.',
    about_disclaimer_title: 'Important Disclaimer',
    about_disclaimer: 'All information on Nabta is for educational purposes only and does not constitute medical advice. Always consult a qualified healthcare provider before starting any herbal regimen, especially if pregnant, nursing, or taking medications.',
    footer_privacy: 'Privacy Policy', footer_sourcing: 'Ethical Sourcing',
    footer_references: 'Scientific References', footer_contact: 'Contact',
    footer_copy: '© 2026 Nabta. All rights reserved.',
    chat_title: 'Botanical Guide', chat_powered: 'Powered by Nabta AI',
    chat_placeholder: 'Ask about herbs, symptoms...',
    chat_disclaimer: 'Educational info only • Not medical advice',
    chat_welcome: "Hello! 🌿 I'm your Nabta botanical guide. I can help you explore herbal remedies, understand plant benefits, and match botanicals to your wellness needs. What would you like to learn about today?",
    chat_suggest_1: 'Boost my immunity', chat_suggest_2: 'Help with digestion',
    chat_suggest_3: "I'm stressed", chat_suggest_4: 'Cough remedies',
    not_found: 'Not found', back_categories: '← Back to Categories',
    botanical_category: 'Botanical Category', coming_soon: 'Plants coming soon to this collection.',
    loading: 'Loading...', view_collection: 'View Collection', most_popular: 'Most Popular',
    botanical_directory: 'Botanical Directory', more_profiles: 'More profiles are currently being researched for this collection.',
    part_of_collection: 'Part of Collection',
    sub_menstrual: 'Menstrual Health', sub_pregnancy: 'Pregnancy Support Plants',
    sub_breastfeeding: 'Breast Feeding Support Plants', sub_haircare: 'Hair Care Plants',
    sub_skincare: 'Skin Care Plants', sub_constipation: 'Constipation Relief Plants',
    sub_diarrhea: 'Diarrhea Support Plants', sub_dyspepsia: 'Dyspepsia',
    sub_ibs: 'IBS', sub_cold: 'Cold', sub_rhinitis: 'Rhinitis',
    sub_sinusitis: 'Sinusitis', sub_cough: 'Cough',
    sub_immune: 'Immune Boosting Plants', sub_antioxidant: 'Anti-Oxidant Rich Plants',
    sub_antiinflammatory: 'Anti-Inflammatory Plants',
  },
  ar: {
    brand: 'نبتة', tagline: 'معهد الأبحاث النباتية',
    nav_discover: 'اكتشف', nav_categories: 'التصنيفات', nav_journal: 'المجلة',
    nav_about: 'عن المعهد', nav_consult: 'استشر خبيراً', nav_switchLang: 'En',
    home_hero_title: 'حكمة الطبيعة،\nمُكتنَزةٌ علمياً.',
    home_hero_sub: 'استكشف التقاء الطب العشبي التقليدي بالبحث السريري الحديث. ارتقِ بصحتك من خلال التعليم النباتي المنتقى القائم على الأدلة.',
    home_cta_explore: 'استكشف الموسوعة', home_cta_journal: 'اقرأ أحدث المجلات',
    home_sleep_title: 'النوم والهدوء', home_sleep_desc: 'حلفاء نباتيون لتهدئة العقل وتخفيف التوتر وتعزيز النوم التصافي. اكتشف الصبغات والشاي المحتوي على فاليريان والبابونج والأشواغاندا.',
    home_immunity_title: 'المناعة', home_immunity_desc: 'عزّز دفاعاتك الطبيعية بمستخلصات قوية من إشنسا والتوت الأكبر والفطريات الطبية.',
    home_vitality_title: 'الحيوية', home_vitality_desc: 'أيقظ احتياطيات الطاقة الطبيعية وادعم التحمل. مجموعة مختارة من الأعشاب المنشطة بما فيها الجينسنغ والروديولا والإليوثيرو.',
    home_digestion_title: 'الهضم', home_digestion_desc: 'هدّئ الجهاز الهضمي وحسّن أداءه بالمقويات المُرّة والكارميناتيف كالزنجبيل والنعناع.',
    home_potm_badge: 'نبتة الشهر', home_potm_latin: 'Echinacea purpurea',
    home_potm_desc: 'تُعدّ الإشنسا في طليعة الأبحاث الوقائية الطبيعية بفضل خصائصها المُعدِّلة للمناعة. تفحص مراجعتنا المنهجية الأخيرة...',
    home_view_profile: 'عرض الملف الكامل', home_explore: 'استكشف المجموعة',
    cats_title: 'مجموعات الصيدلية',
    cats_sub: 'استكشف تصنيفاتنا المنتقاة من المستحضرات النباتية، المصمّمة لدعم جوانب محددة من صحتك. تستند كل مجموعة إلى السلطة العلمية والأناقة العضوية التقليدية.',
    cats_explore: 'استكشف المجموعة',
    cat_immunity_name: 'المناعة', cat_immunity_tagline: 'عزّز دفاعاتك الطبيعية بمستخلصات قوية من الإشنسا والتوت الأكبر والفطريات الطبية.',
    cat_immunity_long: 'اكتشف المدافعين الأقوياء في الطبيعة. هذه المجموعة المنتقاة من النباتات الطبية استُخدمت تقليدياً لتعزيز الدفاعات الطبيعية للجسم، وتقديم نهج شمولي للحفاظ على الصحة والحيوية على مدار الفصول.',
    cat_digestive_name: 'صحة الجهاز الهضمي', cat_digestive_tagline: 'هدّئ الجهاز الهضمي وحسّن أداءه بالمقويات المرة والكارميناتيف كالزنجبيل والنعناع.',
    cat_digestive_long: 'ادعم صحتك الهضمية بالمستحضرات العشبية المجرّبة عبر الزمن. من المقويات المرة التي تحفّز إنزيمات الهضم إلى الكارميناتيف التي تخفف الانزعاج، تدعم هذه النباتات كل جانب من جوانب الهضم الصحي.',
    cat_respiratory_name: 'صحة الجهاز التنفسي', cat_respiratory_tagline: 'ادعم مجرى الهواء الصحي والتنفس السليم بالمستحضرات النباتية المجرّبة.',
    cat_respiratory_long: 'تنفّس بحرية أكبر بدعم نباتي لجهازك التنفسي. تساعد هذه الأعشاب العريقة على الحفاظ على مجرى هواء صافٍ وتهدئة الأغشية المخاطية المتهيجة ودعم صحة الرئة خلال التحديات الموسمية.',
    cat_womens_name: "صحة المرأة", cat_womens_tagline: 'ادعمي التوازن الهرموني والدورة الشهرية والحيوية بحلفاء نباتيين منتقين بعناية.',
    cat_womens_long: 'مجموعة مدروسة من النباتات التي دعمت صحة المرأة عبر الثقافات والقرون. تعالج هذه النباتات التوازن الهرموني وراحة الدورة الشهرية والتحولات في حياة المرأة بحكمة نباتية لطيفة.',
    plant_view_profile: 'عرض الملف', plant_save: 'حفظ النبتة',
    plant_save_journal: 'حفظ في المجلة', plant_history: 'التاريخ والأصل',
    plant_benefits: 'الفوائد العلمية',
    plant_pharmacology_intro: 'بدأ علم الصيدلة الحديث في التحقق مما عرفه المعالجون التقليديون منذ آلاف السنين. المركبات الفعّالة الأساسية هي المسؤولة عن التأثيرات العلاجية الموثّقة.',
    plant_preparation: 'طرق التحضير', plant_symptoms: 'الأعراض المرتبطة',
    plant_related: 'نباتات ذات صلة', plant_botanical_facts: 'الحقائق النباتية',
    plant_family: 'العائلة', plant_native: 'المنطقة الأصلية', plant_growth: 'عادة النمو',
    plant_compounds: 'المركبات الفعّالة', plant_cultivation: 'ملاحظات الزراعة',
    plant_part_of: 'جزء من مجموعة', plant_best_for: 'الأفضل لـ',
    q_title: 'رؤى صحة المجتمع', q_sub: 'بيانات مجمّعة من ردود الاستبيان — تُحدَّث في الوقت الفعلي.',
    q_chart_symptoms: 'الأعراض الأكثر إبلاغاً', q_chart_symptoms_sub: 'مجموع ردود المجتمع',
    q_chart_categories: 'الاهتمام بالتصنيفات', q_chart_categories_sub: 'توزيع مجالات اهتمام المستخدمين',
    q_chart_trends: 'اتجاهات التفاعل الصحي', q_chart_trends_sub: 'النمو الشهري في المستخدمين والنباتات المستكشَفة',
    q_tab_questionnaire: 'الاستبيان', q_tab_results: 'نتائجي',
    q_step_of: 'الخطوة', q_of: 'من', q_complete: 'مكتمل',
    q_back: 'رجوع', q_continue: 'متابعة', q_finish: 'احصل على توصياتي',
    q_start: 'ابدأ الاستبيان →', q_no_results: 'أكمل الاستبيان لرؤية نتائجك.',
    q_users: 'مستخدمون نشطون', q_plants_explored: 'نباتات مستكشَفة',
    qq1_q: 'ما هو اهتمامك الصحي الأساسي؟', qq1_sub: 'اختر المجال الأهم لك الآن.',
    qq2_q: 'ما الأعراض التي تعانيها حالياً؟', qq2_sub: 'اختر كل ما ينطبق عليك.',
    qq3_q: 'كيف تصف نمط حياتك الحالي؟', qq3_sub: 'يساعدنا ذلك في تخصيص التوصيات لوضعك.',
    qq4_q: 'ما مستوى تجربتك في الطب العشبي؟', qq4_sub: 'سنطابق التوصيات مع مستوى راحتك.',
    qq5_q: 'ما هدفك الصحي الأساسي؟', qq5_sub: 'اختر النتيجة الأهم لك.',
    opt_immunity: 'دعم المناعة', opt_immunity_desc: 'تعزيز الدفاعات',
    opt_digestive: 'صحة الجهاز الهضمي', opt_digestive_desc: 'راحة الأمعاء ووظائفها',
    opt_respiratory: 'صحة الجهاز التنفسي', opt_respiratory_desc: 'التنفس والمجاري الهوائية',
    opt_womens: 'صحة المرأة', opt_womens_desc: 'الصحة الهرمونية والدورة الشهرية',
    opt_stress: 'التوتر والطاقة', opt_stress_desc: 'الحيوية الذهنية والجسدية',
    opt_sleep: 'جودة النوم', opt_sleep_desc: 'الراحة والتعافي',
    opt_fatigue: 'الإرهاق', opt_anxiety: 'القلق / التوتر', opt_poor_sleep: 'اضطراب النوم',
    opt_digestive_issues: 'مشاكل هضمية', opt_ibs: 'القولون العصبي / الانتفاخ',
    opt_cough: 'السعال / البرد', opt_low_immunity: 'ضعف المناعة', opt_hormonal: 'خلل هرموني',
    opt_sedentary: 'خامل في الغالب', opt_sedentary_desc: 'جلوس مكتبي، تمارين قليلة',
    opt_moderate: 'نشط باعتدال', opt_moderate_desc: 'تمارين خفيفة 2-3 مرات أسبوعياً',
    opt_active: 'نشط جداً', opt_active_desc: 'تمارين مكثفة منتظمة',
    opt_high_stress: 'ضغط عالٍ', opt_high_stress_desc: 'متطلبات عمل وحياة شاقة',
    opt_beginner: 'مبتدئ تماماً', opt_beginner_desc: 'جديد على عالم الأعشاب',
    opt_some: 'بعض الخبرة', opt_some_desc: 'استخدمت شاياً أو مكملات',
    opt_experienced: 'خبير', opt_experienced_desc: 'ملمّ بالصبغات والأعشاب',
    opt_prevention: 'الوقاية', opt_prevention_desc: 'الحفاظ على الصحة وحمايتها',
    opt_acute: 'معالجة مشاكل حادة', opt_acute_desc: 'حلّ الأعراض الحالية',
    opt_longterm: 'حيوية طويلة الأمد', opt_longterm_desc: 'بناء صحة دائمة',
    opt_education: 'التعلم والاستكشاف', opt_education_desc: 'فهم الطب النباتي',
    res_title: 'ملفك النباتي', res_sub: 'بناءً على ردودك، إليك توصياتك النباتية الشخصية.',
    res_focus: 'مجال التركيز', res_symptoms: 'الأعراض الرئيسية',
    res_recommended: 'النباتات الموصى بها لك', res_explore_all: 'استكشف جميع التصنيفات',
    res_retake: 'أعد الاستبيان',
    res_disclaimer: '⚠️ هذه التوصيات لأغراض تعليمية فقط. استشر دائماً مقدم الرعاية الصحية المؤهل.',
    about_title: 'عن نبتة', about_sub: 'نبتة معهد بحثي نباتي يهدف إلى سد الفجوة بين الحكمة العشبية التقليدية والعلم السريري الحديث.',
    about_evidence: 'قائم على الأدلة', about_evidence_desc: 'كل ملف نباتي مستند إلى بحث علمي محكّم واستخدام سريري تقليدي.',
    about_sourced: 'مستدام أخلاقياً', about_sourced_desc: 'نتشارك مع مزارعين مسؤولين يمارسون الزراعة المستدامة والتجديدية.',
    about_education: 'تعليم نباتي', about_education_desc: 'هدفنا تمكين المعرفة — لا استبدال الرعاية الطبية.',
    about_disclaimer_title: 'إخلاء مسؤولية مهم',
    about_disclaimer: 'جميع المعلومات على نبتة لأغراض تعليمية فقط ولا تُعدّ نصيحة طبية. استشر دائماً مقدم رعاية صحية مؤهلاً قبل البدء بأي نظام عشبي.',
    footer_privacy: 'سياسة الخصوصية', footer_sourcing: 'الاستدامة الأخلاقية',
    footer_references: 'المراجع العلمية', footer_contact: 'اتصل بنا',
    footer_copy: '© 2026 نبتة. جميع الحقوق محفوظة.',
    chat_title: 'المرشد النباتي', chat_powered: 'مدعوم من نبتة AI',
    chat_placeholder: 'اسأل عن الأعشاب أو الأعراض...',
    chat_disclaimer: 'معلومات تعليمية فقط • ليست نصيحة طبية',
    chat_welcome: 'مرحباً! 🌿 أنا مرشدك النباتي في نبتة. يمكنني مساعدتك في استكشاف العلاجات العشبية وفهم فوائد النباتات ومطابقة النباتات لاحتياجاتك الصحية. عمَّ تودّ التعلم اليوم؟',
    chat_suggest_1: 'تعزيز مناعتي', chat_suggest_2: 'مساعدة في الهضم',
    chat_suggest_3: 'أعاني من التوتر', chat_suggest_4: 'علاجات السعال',
    not_found: 'غير موجود', back_categories: '← العودة إلى التصنيفات',
    botanical_category: 'تصنيف نباتي', coming_soon: 'النباتات قادمة قريباً إلى هذه المجموعة.',
    loading: 'جارٍ التحميل...', view_collection: 'عرض المجموعة', most_popular: 'الأكثر شيوعاً',
    botanical_directory: 'الدليل النباتي', more_profiles: 'مزيد من الملفات قيد البحث لهذه المجموعة.',
    part_of_collection: 'جزء من مجموعة',
    sub_menstrual: 'صحة الدورة الشهرية', sub_pregnancy: 'نباتات دعم الحمل',
    sub_breastfeeding: 'نباتات دعم الرضاعة', sub_haircare: 'نباتات العناية بالشعر',
    sub_skincare: 'نباتات العناية بالبشرة', sub_constipation: 'نباتات تخفيف الإمساك',
    sub_diarrhea: 'نباتات دعم الإسهال', sub_dyspepsia: 'عسر الهضم',
    sub_ibs: 'القولون العصبي', sub_cold: 'البرد', sub_rhinitis: 'التهاب الأنف',
    sub_sinusitis: 'التهاب الجيوب الأنفية', sub_cough: 'السعال',
    sub_immune: 'نباتات تقوية المناعة', sub_antioxidant: 'نباتات غنية بمضادات الأكسدة',
    sub_antiinflammatory: 'نباتات مضادة للالتهابات',
  },
};

export const PLANT_TRANSLATIONS = {
  ar: {
    echinacea: {
      name: 'إشنسا', shortDescription: 'مشهورة بقدرتها على تحفيز الجهاز المناعي، فعّالة بشكل خاص عند تناولها عند أول ظهور للأعراض الموسمية.',
      description: 'ركيزة أساسية في العلاج العشبي التقليدي، تقف الإشنسا في طليعة الأبحاث الوقائية الطبيعية. تم التحقق من خصائصها المناعية في دراسات سريرية عديدة.',
      history: 'يعود الاستخدام الطبي للإشنسا إلى الشعوب الأصلية في أمريكا الشمالية، الذين استخدموها لأمراض متعددة. قُدِّمت للمستوطنين الأوروبيين وأصبحت من أشهر الأعشاب الطبية في الولايات المتحدة.',
      benefits: [
        { icon: 'shield', title: 'تحفيز المناعة', desc: 'تنشّط الضامّات وتزيد إنتاج الخلايا التائية، مما يعزز الاستجابة المناعية الفطرية.' },
        { icon: 'healing', title: 'مضاد للالتهابات', desc: 'تحتوي على حمض الشيكوريك والألكيلاميدات التي تقلل السيتوكينات الالتهابية.' },
        { icon: 'coronavirus', title: 'مضاد للفيروسات', desc: 'تُظهر الأبحاث فعاليتها ضد طيف واسع من فيروسات الجهاز التنفسي.' },
      ],
      botanicalFacts: { family: 'الفصيلة النجمية', nativeRegion: 'أمريكا الشمالية', growthHabit: 'نبات عشبي معمر', activeCompounds: 'الألكيلاميدات، مشتقات حمض الكافيك', cultivationNotes: 'تنمو في تربة جيدة التصريف مع أشعة الشمس الكاملة. تُزهر في منتصف الصيف.' },
      preparation: [
        { method: 'الصبغة', desc: 'مستخلص كحولي بجرعة 2-4 مل، 3 مرات يومياً عند ظهور الأعراض.', bestFor: 'التنشيط المناعي السريع' },
        { method: 'الشاي', desc: 'انقع ملعقة إلى ملعقتين من العشب الجاف في ماء مغلٍ لمدة 10 دقائق.', bestFor: 'الدعم الوقائي' },
      ],
      symptoms: ['سعال', 'برد', 'مناعة', 'جهاز تنفسي'],
    },
    elderberry: {
      name: 'التوت الأكبر', shortDescription: 'غني بمضادات الأكسدة والفيتامينات، هذه التوت الداكن تقليد أصيل لتهدئة أعراض البرد وتعزيز المرونة الشتوية.',
      description: 'التوت الأكبر (Sambucus nigra) له تاريخ طويل في الطب العشبي الأوروبي. التوت الداكن غني للغاية بالأنثوسيانين وفيتامين C والفلافونويدات.',
      history: 'عرفه أبقراط بـ"صندوق دواء أهل الريف"، واستُخدم طبياً لآلاف السنين. كان جزءاً محورياً من الطب الشعبي الأوروبي للبرد والأنفلونزا والحمى.',
      benefits: [
        { icon: 'coronavirus', title: 'مضاد للفيروسات', desc: 'ترتبط الفلافونويدات بالجزيئات الفيروسية وتمنعها من دخول خلايا المضيف.' },
        { icon: 'favorite', title: 'غني بمضادات الأكسدة', desc: 'من بين أعلى محتوى مضادات الأكسدة في أي توت، يحمي الخلايا من التلف.' },
        { icon: 'thermostat', title: 'دعم الحمى', desc: 'استخدام تقليدي لخفض الحمى عبر التعرق.' },
      ],
      botanicalFacts: { family: 'فصيلة المسكية', nativeRegion: 'أوروبا، شمال أفريقيا، غرب آسيا', growthHabit: 'شجيرة نفضية', activeCompounds: 'الأنثوسيانين، الكيرستين، الروتين', cultivationNotes: 'تنمو في تربة رطبة خصبة. ضوء شمس كامل إلى جزئي.' },
      preparation: [
        { method: 'الشراب', desc: 'اطبخ التوت مع الماء والعسل حتى يصبح مركّزاً. ملعقة كبيرة يومياً وقائياً.', bestFor: 'صيانة المناعة اليومية' },
        { method: 'الصبغة', desc: 'مستخلص كحولي يوفر تركيزاً من الأنثوسيانين. 2-4 مل، 3 مرات يومياً.', bestFor: 'دعم العدوى الفعّالة' },
      ],
      symptoms: ['برد', 'أنفلونزا', 'مناعة', 'سعال'],
    },
    astragalus: {
      name: 'الأستراغالوس', shortDescription: 'جذر مُكيِّف قوي مستخدم في الطب الصيني التقليدي لبناء المناعة الأساسية والحماية من الإجهاد.',
      description: 'الأستراغالوس من أهم الأعشاب في الطب الصيني التقليدي، مُستخدَم منذ أكثر من 2000 عام. بوصفه مُكيِّفاً، يساعد الجسم على الاستجابة للتوتر مع تعزيز المناعة.',
      history: 'يُعرف بـ"هوانغ تشي" في الطب الصيني التقليدي، واعتُبر عشباً رئيسياً للطب الصيني لآلاف السنين.',
      benefits: [
        { icon: 'shield', title: 'تعديل المناعة', desc: 'تزيد السكريات المتعددة إنتاج خلايا الدم البيضاء وتعزز نشاط خلايا NK.' },
        { icon: 'psychology', title: 'مُكيِّف', desc: 'يساعد في تطبيع الاستجابة الفسيولوجية للجسم للتوتر، ويقلل الكورتيزول.' },
        { icon: 'favorite', title: 'دعم القلب والأوعية', desc: 'تحسّن الأستراغالوسيدات وظيفة القلب وتحمي خلايا عضلة القلب.' },
      ],
      botanicalFacts: { family: 'الفصيلة البقولية', nativeRegion: 'الصين، منغوليا، كوريا', growthHabit: 'نبات عشبي معمر', activeCompounds: 'الأستراغالوسيدات، السكريات المتعددة، الصابونين', cultivationNotes: 'يفضّل التربة الرملية جيدة التصريف. يتحمل الجفاف بعد التأسيس.' },
      preparation: [
        { method: 'الطبيخ', desc: 'اطبخ شرائح الجذر في الماء لمدة 30-45 دقيقة. أضفه للحساء كمقوٍّ يومي.', bestFor: 'بناء المناعة طويل الأمد' },
        { method: 'الكبسولات', desc: 'كبسولات مستخلص موحّد. 500-1500 مغ يومياً.', bestFor: 'التكمّل اليومي المريح' },
      ],
      symptoms: ['مناعة', 'إرهاق', 'توتر'],
    },
    reishi: {
      name: 'ريشي', shortDescription: 'يُعرف بـ"فطر الخلود"، يعدّل ريشي وظيفة المناعة ويعزز الاسترخاء العميق وتوازن الجهاز العصبي.',
      description: 'فطر الريشي يُجلَّل في الثقافات الشرق آسيوية منذ أكثر من 2000 عام رمزاً للعمر المديد والقوة الروحية.',
      history: 'يُسمى "لينغ تشي" بالصينية أي "عشب القوة الروحية"، وكان محجوزاً للأباطرة والنبلاء تاريخياً.',
      benefits: [
        { icon: 'shield', title: 'تعديل المناعة', desc: 'تحفّز البيتا-غلوكان الاستجابة المناعية وتنظّمها دون إفراط في التحفيز.' },
        { icon: 'psychology', title: 'مُكيِّف عصبي', desc: 'تعزز التربينات اليقظة الهادئة وتحسّن جودة النوم.' },
        { icon: 'favorite', title: 'حامٍ للكبد', desc: 'يحمي خلايا الكبد من التلف ويدعم نشاط إنزيمات إزالة السموم.' },
      ],
      botanicalFacts: { family: 'فصيلة الغانوديرمية', nativeRegion: 'شرق آسيا، موزّع عالمياً', growthHabit: 'فطر خشبي', activeCompounds: 'البيتا-غلوكان، التربينات، أحماض الغانوديريك', cultivationNotes: 'ينمو على أجذاع الأشجار الصلبة. يفضّل البيئات الدافئة والرطبة.' },
      preparation: [
        { method: 'المستخلص المزدوج', desc: 'استخلاص بالماء الساخن + الكحول. 1-2 مل يومياً.', bestFor: 'الفائدة الشاملة' },
        { method: 'الشاي', desc: 'اطبخ الفطر المقطّع لمدة ساعتين. يمكن إخفاء طعمه المر.', bestFor: 'التحضير التقليدي' },
      ],
      symptoms: ['مناعة', 'توتر', 'نوم', 'إرهاق'],
    },
    oregano: {
      name: 'الأوريغانو', shortDescription: 'قوي وعطري، يُعدّ زيت الأوريغانو بالغ الأهمية لخصائصه القوية المضادة للميكروبات والفيروسات.',
      description: 'رغم كونه عشباً طبخياً مألوفاً، يمتلك الأوريغانو خصائص طبية استثنائية. يُظهر زيته الأساسي نشاطاً قوياً مضاداً للميكروبات والفطريات والفيروسات.',
      history: 'أجلّه الإغريق القدماء رمزاً للسعادة واستخدموه طبياً. اسمه مشتق من "أوروس" (جبل) و"غانوس" (فرح).',
      benefits: [
        { icon: 'coronavirus', title: 'مضاد للميكروبات', desc: 'يُعطّل الكارفاكرول غشاء خلية البكتيريا، مع فعالية ضد السلالات المقاومة للأدوية.' },
        { icon: 'healing', title: 'مضاد للفطريات', desc: 'فعالية موثّقة ضد أنواع المبيضات والعدوى الفطرية الأخرى.' },
        { icon: 'shield', title: 'مضاد للأكسدة', desc: 'من أعلى درجات ORAC بين الأعشاب، بنشاط مضاد للأكسدة يفوق التوت الأزرق 4 مرات.' },
      ],
      botanicalFacts: { family: 'فصيلة الشفوية', nativeRegion: 'البحر المتوسط، غرب آسيا', growthHabit: 'نبات عشبي معمر', activeCompounds: 'الكارفاكرول، الثيمول، حمض الروزمارينيك', cultivationNotes: 'يزدهر في تربة فقيرة جيدة التصريف مع أشعة شمس كاملة.' },
      preparation: [
        { method: 'زيت الأوريغانو', desc: 'زيت أساسي مخفَّف (1-2 قطرات في زيت ناقل). خلال العدوى الحادة فقط.', bestFor: 'عدوى ميكروبية فعّالة' },
        { method: 'الشاي', desc: 'انقع ملعقة صغيرة أوريغانو مجفف في ماء ساخن 5-7 دقائق.', bestFor: 'دعم الجهاز التنفسي والمناعة' },
      ],
      symptoms: ['مناعة', 'سعال', 'جهاز تنفسي'],
    },
    ginger: {
      name: 'الزنجبيل', shortDescription: 'جذمور دافئ يحفّز الدورة الدموية ويساعد الهضم ويمتلك خصائص قوية مضادة للالتهابات.',
      description: 'الزنجبيل واحد من أكثر النباتات الطبية دراسةً على وجه الأرض. يحتوي جذموره الحار على مركبات فعّالة قوية مسؤولة عن تأثيراته العلاجية الواسعة.',
      history: 'زُرع الزنجبيل واستُخدم طبياً منذ أكثر من 5000 عام. كان من أوائل البهارات التي وصلت أوروبا من آسيا.',
      benefits: [
        { icon: 'restaurant', title: 'مساعد هضمي', desc: 'يحفّز إنتاج اللعاب والصفراء وإنزيمات الهضم، مما يسرّع إفراغ المعدة ويقلل الغثيان.' },
        { icon: 'healing', title: 'مضاد للالتهابات', desc: 'تثبّط الجينجيرولات إنزيمات الالتهاب مقارنةً بمضادات الالتهاب غير الستيرويدية دون آثار جانبية.' },
        { icon: 'thermostat', title: 'منبّه للدورة الدموية', desc: 'يزيد الدورة الدموية الطرفية ويعزز التعرق الصحي أثناء الحمى.' },
      ],
      botanicalFacts: { family: 'فصيلة الزنجبيلية', nativeRegion: 'جنوب شرق آسيا', growthHabit: 'جذمور عشبي معمر', activeCompounds: 'الجينجيرول، الشوغاول، الزنجيرون', cultivationNotes: 'نبات استوائي يحتاج ظروفاً دافئة رطبة وتربة غنية جيدة التصريف.' },
      preparation: [
        { method: 'شاي الطازج', desc: 'ابشر إصبعاً من الزنجبيل الطازج في ماء مغلٍ، انقعه 10 دقائق. أضف العسل والليمون.', bestFor: 'الغثيان وعدم الراحة الهضمية' },
        { method: 'الصبغة', desc: 'صبغة الجذر الطازج في الكحول. 2-4 مل قبل الوجبات.', bestFor: 'الاستخدام اليومي المستمر' },
      ],
      symptoms: ['غثيان', 'قولون عصبي', 'إمساك', 'سعال', 'مناعة'],
    },
    peppermint: {
      name: 'النعناع', shortDescription: 'عشب هضمي محبوب يرخّي العضلات الملساء ويخفف أعراض القولون العصبي ويوفر راحة منعشة.',
      description: 'النعناع من أكثر الأعشاب الطبية بحثاً علمياً، خاصةً للحالات الهضمية. مادته الفعّالة الأساسية المنثول يعمل كمانع لقنوات الكالسيوم على العضلات الملساء المعوية.',
      history: 'هجين طبيعي من النعناع المائي والنعناع الأخضر، وُصف لأول مرة في إنجلترا عام 1696.',
      benefits: [
        { icon: 'nutrition', title: 'تخفيف القولون العصبي', desc: 'أثبتت كبسولات مغلفة في تجارب سريرية متعددة تخفيفاً ملحوظاً لأعراض القولون العصبي.' },
        { icon: 'psychology', title: 'وضوح ذهني', desc: 'استنشاق المنثول يحسّن اليقظة والذاكرة وسرعة المعالجة.' },
        { icon: 'healing', title: 'مضاد للتشنج', desc: 'يرخّي العضلات الملساء في الجهاز الهضمي، مما يقلل التشنج والانتفاخ.' },
      ],
      botanicalFacts: { family: 'فصيلة الشفوية', nativeRegion: 'أوروبا والشرق الأوسط (هجين)', growthHabit: 'نبات معمر ريزومي', activeCompounds: 'المنثول، المنثون، حمض الروزمارينيك', cultivationNotes: 'ينمو بقوة في تربة رطبة غنية. ينتشر بقوة عبر الجذامير.' },
      preparation: [
        { method: 'الشاي', desc: 'انقع ملعقة إلى ملعقتين من الأوراق لمدة 5-7 دقائق. اشرب بعد الوجبات.', bestFor: 'راحة هضمية بعد الأكل' },
        { method: 'الكبسولات المعوية', desc: 'كبسولات مغلفة تتجاوز المعدة للعمل مباشرةً في الأمعاء. 0.2-0.4 مل، 3 مرات يومياً.', bestFor: 'إدارة أعراض القولون العصبي' },
      ],
      symptoms: ['قولون عصبي', 'إمساك', 'غثيان', 'صداع'],
    },
    chamomile: {
      name: 'البابونج', shortDescription: 'حليف عصبي وهضمي لطيف، يهدّئ ارتباط الأمعاء بالجهاز العصبي بخصائص مضادة للالتهابات ومهدّئة.',
      description: 'مظهر البابونج الرقيق يخفي ملفاً طبياً متطوراً. يحتوي بابونج ألماني على الكامازولين ومركب الأبيجنين الذي يرتبط بمستقبلات GABA في الدماغ.',
      history: 'واحد من أقدم الأعشاب الطبية في التاريخ المسجّل، يظهر في الدساتير الطبية المصرية القديمة واليونانية والرومانية.',
      benefits: [
        { icon: 'psychology', title: 'مضاد للقلق', desc: 'يرتبط الأبيجنين بمستقبلات GABA، محدثاً تأثيرات مهدئة خفيفة دون إدمان.' },
        { icon: 'nutrition', title: 'منشّط هضمي', desc: 'تحفّز المواد المرة إفرازات الجهاز الهضمي بينما تخفف مضادات التشنج التقلصات.' },
        { icon: 'healing', title: 'مضاد للالتهابات', desc: 'يوفر الكامازولين والبيسابولول تأثيراً قوياً مضاداً للالتهابات.' },
      ],
      botanicalFacts: { family: 'الفصيلة النجمية', nativeRegion: 'غرب أوروبا، غرب آسيا', growthHabit: 'عشب حولي', activeCompounds: 'الكامازولين، الأبيجنين، البيسابولول', cultivationNotes: 'نبات ذاتي البذور يزدهر في تربة جافة فقيرة مع أشعة شمس كاملة.' },
      preparation: [
        { method: 'الشاي', desc: 'انقع 2-3 ملاعق من الأزهار في ماء قارب الغليان لمدة 5 دقائق مغطى. اشرب قبل النوم.', bestFor: 'دعم النوم والهدوء الهضمي' },
        { method: 'الصبغة', desc: '2-4 مل في الماء، 3 مرات يومياً للقلق أو الحالات الهضمية.', bestFor: 'القلق والقولون العصبي' },
      ],
      symptoms: ['قولون عصبي', 'توتر', 'نوم', 'قلق', 'إمساك'],
    },
    fennel: {
      name: 'الشمر', shortDescription: 'كارميناتيف هضمي كلاسيكي يخفف الغازات والانتفاخ والتشنجات المعوية.',
      description: 'الشمر واحد من أكثر الأعشاب الهضمية استخداماً. مركبه الأساسي الأنيثول يوفر تأثيراً كارميناتيفاً مباشراً بإرخاء العضلات الملساء في الأمعاء.',
      history: 'زُرع الشمر واستُخدم طبياً وطهوياً منذ 4000 عام على الأقل. استخدمه المصريون والصينيون القدماء للشكاوى الهضمية.',
      benefits: [
        { icon: 'nutrition', title: 'كارميناتيف', desc: 'الأنيثول يرخّي العضلات الملساء المعوية مباشرةً، مُحرِّراً الغازات ومُخفِّفاً الانتفاخ.' },
        { icon: 'restaurant', title: 'منبّه هضمي', desc: 'يحفّز إنتاج الصفراء وإفراز إنزيمات الهضم.' },
        { icon: 'favorite', title: 'مضاد للتشنج', desc: 'فعّال لمغص الرضّع وتشنجات الحيض وتشنجات القولون العصبي.' },
      ],
      botanicalFacts: { family: 'فصيلة الخيمية', nativeRegion: 'البحر المتوسط', growthHabit: 'عشب معمر صلب', activeCompounds: 'الأنيثول، الفنشون، الإستراغول', cultivationNotes: 'أشعة شمس كاملة، تربة جيدة التصريف. ابعده عن الشبت لمنع التلقيح المتقاطع.' },
      preparation: [
        { method: 'شاي البذور', desc: 'احطم ملعقة من البذور وانقعها في ماء مغلٍ لمدة 10 دقائق. اشرب بعد الوجبات.', bestFor: 'الغازات والانتفاخ بعد الأكل' },
        { method: 'العصير الطازج', desc: 'اعصر بصلة شمر طازجة مع التفاح والزنجبيل لتحضير جرعة منشّطة للهضم.', bestFor: 'تنشيط الهضم' },
      ],
      symptoms: ['قولون عصبي', 'إمساك', 'غازات', 'انتفاخ'],
    },
    dandelion: {
      name: 'الهندباء', shortDescription: 'منشّط مرّ قوي يحفّز وظيفة الكبد ويدعم إنتاج الصفراء ويُطهّر الجهاز الهضمي بلطف.',
      description: 'الهندباء من أكمل النباتات الدوائية المتاحة، إذ تقدم كل أجزائها—الجذر والورق والزهرة—تأثيرات طبية مميزة.',
      history: 'استُخدمت طبياً لأكثر من 1000 عام في التقاليد الأوروبية والصينية والأمريكية الأصلية.',
      benefits: [
        { icon: 'nutrition', title: 'منشّط الكبد', desc: 'المركبات المرة تحفّز إنتاج الصفراء، مما يدعم هضم الدهون وتطهير الكبد.' },
        { icon: 'water_drop', title: 'مُدرّ طبيعي للبول', desc: 'مستخلص الورق يزيد إدرار البول مع توفير البوتاسيوم لتعويض الإلكتروليت.' },
        { icon: 'eco', title: 'كثيف المغذيات', desc: 'غني بالفيتامينات A وC وK والحديد والكالسيوم.' },
      ],
      botanicalFacts: { family: 'الفصيلة النجمية', nativeRegion: 'أوروبا، آسيا (متطبّع عالمياً)', growthHabit: 'نبات عشبي معمر', activeCompounds: 'تاراكسين، تاراكسيرين، إينولين', cultivationNotes: 'ينمو في أي تربة تقريباً. تُحصد الجذور في الخريف للدواء.' },
      preparation: [
        { method: 'طبيخ الجذر', desc: 'اطبخ ملعقة من الجذر المقطّع في كوبين ماء لمدة 20 دقيقة. اشرب 2-3 أكواب يومياً.', bestFor: 'دعم الكبد والهضم' },
        { method: 'شاي الورق', desc: 'انقع الأوراق الطازجة أو المجففة لمدة 10 دقائق. مرّ قليلاً ومنظّف.', bestFor: 'تطهير يومي لطيف' },
      ],
      symptoms: ['إمساك', 'قولون عصبي', 'إرهاق', 'انتفاخ'],
    },
    thyme: {
      name: 'الزعتر', shortDescription: 'عشب تنفسي قوي يطرد المخاط ويهدّئ السعال ويوفر دعماً مضاداً للميكروبات.',
      description: 'الزعتر واحد من أكثر الأعشاب التنفسية تحققاً سريرياً. مركباته الفعّالة الأساسية توفر تأثيرات طاردة للبلغم ومضادة للتشنج ومضادة للميكروبات.',
      history: 'يعود استخدام الزعتر الطبي إلى مصر القديمة حيث استُخدم في التحنيط. كان الإغريق القدماء يحرقونه بخوراً في المعابد.',
      benefits: [
        { icon: 'air', title: 'طارد للبلغم', desc: 'تحفّز الزيوت المتطايرة إفرازات القصبات وحركة الأهداب، مما يُفكّك البلغم ويُخرجه.' },
        { icon: 'coronavirus', title: 'مضاد للميكروبات', desc: 'الثيمول مطهّر قوي يستخدم في غسولات الفم السريرية.' },
        { icon: 'healing', title: 'مضاد للتشنج', desc: 'يرخّي العضلات الملساء القصبية، مما يوفر راحة من السعال المتشنج.' },
      ],
      botanicalFacts: { family: 'فصيلة الشفوية', nativeRegion: 'جنوب أوروبا، البحر المتوسط', growthHabit: 'شجيرة خشبية معمرة', activeCompounds: 'الثيمول، الكارفاكرول، حمض الروزمارينيك', cultivationNotes: 'ينمو في تربة فقيرة جافة جيدة التصريف مع أشعة شمس كاملة.' },
      preparation: [
        { method: 'الشاي', desc: 'انقع ملعقتين من الزعتر في ماء مغلٍ لمدة 10 دقائق مغطى. اشرب 3 مرات يومياً.', bestFor: 'السعال واحتقان الجهاز التنفسي' },
        { method: 'الاستنشاق بالبخار', desc: 'أضف الزعتر والأوكالبتوس إلى وعاء ماء ساخن. استنشق البخار مع منشفة فوق الرأس.', bestFor: 'احتقان الجيوب والقصبات' },
      ],
      symptoms: ['سعال', 'جهاز تنفسي', 'برد', 'التهاب الشعب'],
    },
    mullein: {
      name: 'العصفار', shortDescription: 'منشّط رئوي لطيف وفعّال، يهدّئ مجاري الهواء المتهيجة ويعزز طرد المخاط.',
      description: 'العصفار من أكثر الأعشاب التنفسية احتراماً في الطب العشبي الغربي. تحتوي أوراقه الكبيرة المزغبة على سكريات مخاطية تُطلّي مجاري الجهاز التنفسي وتهدّئها.',
      history: 'يُعرف بـ"العصفار العظيم" لنعومة أوراقه، استُخدم من قِبل أمريكيي الأصل والأوروبيين على حد سواء لأمراض الرئة.',
      benefits: [
        { icon: 'air', title: 'مُلطِّف', desc: 'يُغلّف المخاط مجاري القصبات المتهيجة ويهدّئها، مما يقلل تهيج السعال.' },
        { icon: 'healing', title: 'طارد للبلغم', desc: 'تُرقّق الصابونين إفرازات القصبات، مما يسهّل طرحها ويخفف الاحتقان.' },
        { icon: 'shield', title: 'مضاد للالتهابات', desc: 'يقلل الالتهاب في الجهاز التنفسي، مفيد للحالات المزمنة كالربو.' },
      ],
      botanicalFacts: { family: 'فصيلة العيون الفتوح', nativeRegion: 'أوروبا، آسيا (متطبّع عالمياً)', growthHabit: 'عشب حولي', activeCompounds: 'المخاط، الصابونين، الفيرباسكوصابونين', cultivationNotes: 'ينمو في التربة المضطربة وجوانب الطرق مع أشعة شمس كاملة.' },
      preparation: [
        { method: 'شاي الأوراق', desc: 'انقع ملعقتين من الأوراق المجففة في ماء مغلٍ لمدة 15 دقيقة. صفِّه جيداً.', bestFor: 'السعال الجاف المتهيج' },
        { method: 'صبغة الجذر', desc: 'صبغة الجذر 2-4 مل لدعم أعمق للجهاز التنفسي.', bestFor: 'الحالات التنفسية المزمنة' },
      ],
      symptoms: ['سعال', 'جهاز تنفسي', 'ربو', 'التهاب الشعب'],
    },
    eucalyptus: {
      name: 'الأوكالبتوس', shortDescription: 'يُعدّ زيت الأوكالبتوس مُزيلاً قوياً للاحتقان وطارداً للبلغم، يُستخدم على نطاق واسع لتصفية الجيوب.',
      description: 'الأوكالبتوس من أكثر النباتات الطبية شهرةً في العالم، خاصةً من خلال زيته الأساسي الغني بالإيكاليبتول المثبت سريرياً.',
      history: 'استخدم السكان الأصليون الأستراليون أوراق الأوكالبتوس لآلاف السنين. اكتشف المستوطنون الأوروبيون قيمته الطبية في القرن الثامن عشر.',
      benefits: [
        { icon: 'air', title: 'مُزيل الاحتقان', desc: '1,8-cineole يكسر المخاط ويقلل الاحتقان الأنفي والقصبي بفعالية.' },
        { icon: 'coronavirus', title: 'مضاد للميكروبات', desc: 'الإيكاليبتول يُظهر نشاطاً مضاداً للبكتيريا والفيروسات.' },
        { icon: 'healing', title: 'مضاد للالتهابات', desc: 'يثبّط الوسطاء الالتهابيين في الجهاز التنفسي.' },
      ],
      botanicalFacts: { family: 'فصيلة الآسية', nativeRegion: 'أستراليا', growthHabit: 'شجرة دائمة الخضرة', activeCompounds: '1,8-cineole (إيكاليبتول)، α-pinene', cultivationNotes: 'شجرة سريعة النمو تتطلب أشعة شمس كاملة وتربة جيدة التصريف.' },
      preparation: [
        { method: 'الاستنشاق بالبخار', desc: 'أضف 3-5 قطرات زيت عطري إلى وعاء ماء ساخن. استنشق لمدة 10 دقائق تحت منشفة.', bestFor: 'احتقان الجيوب والصدر' },
        { method: 'دهان الصدر', desc: 'خفِّف 2-3% زيت عطري في زيت جوز الهند وضعه على منطقة الصدر والحلق.', bestFor: 'راحة تنفسية ليلية' },
      ],
      symptoms: ['جهاز تنفسي', 'سعال', 'التهاب الجيوب', 'برد'],
    },
    vitex: {
      name: 'فيتكس', shortDescription: 'يُعرف بـ"توت شجرة العفة"، يدعم فيتكس التوازن الهرموني ويخفف أعراض متلازمة ما قبل الحيض.',
      description: 'فيتكس العشب الأوروبي الرائد لصحة المرأة الهرمونية. على عكس معظم الأعشاب، يعمل فيتكس على الغدة النخامية لتطبيع مستويات البرولاكتين والبروجسترون.',
      history: 'استُخدم طبياً لأكثر من 2500 عام، ويظهر في كتابات أبقراط وديوسقوريدس.',
      benefits: [
        { icon: 'favorite', title: 'تخفيف متلازمة ما قبل الحيض', desc: 'تُظهر تجارب سريرية عديدة تخفيفاً ملحوظاً في أعراض PMS.' },
        { icon: 'cycle', title: 'تنظيم الدورة', desc: 'يطبّع طول الدورة الشهرية ويقلل الدورات غير المنتظمة.' },
        { icon: 'psychology', title: 'تنظيم البرولاكتين', desc: 'يقلل مستويات البرولاكتين المرتفعة.' },
      ],
      botanicalFacts: { family: 'فصيلة الشفوية', nativeRegion: 'البحر المتوسط، وسط آسيا', growthHabit: 'شجيرة نفضية', activeCompounds: 'الإيريدويدات، الفلافونويدات، الديتيربينات', cultivationNotes: 'يفضّل مناخ البحر المتوسط. أشعة شمس كاملة، تربة جيدة التصريف.' },
      preparation: [
        { method: 'الصبغة', desc: '2-4 مل كل صباح، طويل الأمد (3-6 أشهر على الأقل).', bestFor: 'التنظيم الهرموني' },
        { method: 'الكبسولات', desc: '20-40 مغ مستخلص موحّد يومياً في الصباح.', bestFor: 'دعم PMS والدورة الشهرية' },
      ],
      symptoms: ['متلازمة ما قبل الحيض', 'خلل هرموني', 'دورات غير منتظمة', 'قلق'],
    },
    ashwagandha: {
      name: 'الأشواغاندا', shortDescription: 'عشب قديم مبجّل في الطب الأيورفيدي، مشهور بخصائصه المُكيِّفة العميقة التي تساعد الجسم على التعامل مع التوتر.',
      description: 'عشب قديم مبجّل في الطب الأيورفيدي، الأشواغاندا معروفة بخصائصها المُكيِّفة العميقة. يترجم اسمها إلى "رائحة الحصان" بالسنسكريتية.',
      history: 'يمتد تاريخ الأشواغاندا عبر الطب الأيورفيدي التقليدي منذ أكثر من 3000 عام. موطنها المناطق الجافة في الهند وشمال أفريقيا والشرق الأوسط.',
      benefits: [
        { icon: 'psychology', title: 'تخفيف التوتر والقلق', desc: 'انخفاض ملحوظ في مستويات الكورتيزول، يساعد الجسم على إدارة التوتر الجهازي.' },
        { icon: 'favorite', title: 'دعم القلب والتحمل', desc: 'تشير الدراسات إلى تحسّن في مستويات VO2max لدى البالغين الأصحاء.' },
        { icon: 'neurology', title: 'الوظيفة المعرفية', desc: 'فوائد محتملة للذاكرة وأداء المهام والانتباه.' },
      ],
      botanicalFacts: { family: 'فصيلة الباذنجانية', nativeRegion: 'الهند، الشرق الأوسط، أفريقيا', growthHabit: 'شجيرة دائمة الخضرة صغيرة', activeCompounds: 'الويثانولايدات', cultivationNotes: 'تزدهر في تربة جافة حجرية مع أشعة شمس كاملة. مقاومة عالية للجفاف.' },
      preparation: [
        { method: 'الشاي التقليدي', desc: 'اغلِ ملعقة صغيرة من الجذر المجفف في كوب ماء أو حليب لمدة 10-15 دقيقة. صفِّه وحلِّه بالعسل.', bestFor: 'الهدوء المسائي' },
        { method: 'مستخلصات الصبغة', desc: 'مستخلصات كحولية أو جليسيرينية توفر امتصاصاً عالياً. عادةً 30-40 قطرة يومياً.', bestFor: 'الامتصاص السريع' },
      ],
      symptoms: ['توتر', 'إرهاق', 'مناعة', 'قلق', 'نوم'],
    },
    'red-raspberry': {
      name: 'ورق التوت الأحمر', shortDescription: 'منشّط رحمي مشهور استُخدم لقرون لتقوية الرحم وتسهيل الولادة ودعم الصحة الإنجابية.',
      description: 'يُسمى ورق التوت الأحمر في كثير من الأحيان "عشبة المرأة" لتقارب خصائصه مع الجهاز التناسلي الأنثوي.',
      history: 'استخدمته النساء الأمريكيات الأصليات لقرون ودُوِّن في الطب العشبي الأوروبي منذ القرن السادس عشر.',
      benefits: [
        { icon: 'favorite', title: 'منشّط الرحم', desc: 'قلويد الفراغرين يقوّي ويشدّ عضلة الرحم، تقليدياً للتحضير للولادة.' },
        { icon: 'healing', title: 'غني بالمعادن', desc: 'غني جداً بالمغنيسيوم والبوتاسيوم والحديد والكالسيوم.' },
        { icon: 'eco', title: 'دعم الدورة الشهرية', desc: 'يقلل تشنجات الدورة الشهرية وينظّم طولها.' },
      ],
      botanicalFacts: { family: 'فصيلة الوردية', nativeRegion: 'أوروبا، شمال آسيا', growthHabit: 'شجيرة نفضية', activeCompounds: 'الفراغرين، العفص، الفلافونويدات', cultivationNotes: 'ينمو في المناطق المعتدلة. تُحصد الأوراق في الربيع قبل الإزهار.' },
      preparation: [
        { method: 'شاي الأوراق', desc: 'انقع ملعقة إلى ملعقتين من الأوراق المجففة في ماء مغلٍ لمدة 10-15 دقيقة. اشرب 2-3 أكواب يومياً.', bestFor: 'دعم الحمل والدورة الشهرية' },
        { method: 'الصبغة', desc: '2-4 مل في الماء، 2-3 مرات يومياً. ابدأ في الثلث الثاني فقط واستشيري القابلة.', bestFor: 'التحضير للولادة' },
      ],
      symptoms: ['متلازمة ما قبل الحيض', 'تشنجات الدورة', 'دعم الحمل', 'خلل هرموني'],
    },
    rosemary: {
      name: 'إكليل الجبل', shortDescription: 'ثبت علمياً أنه يحفّز نمو الشعر بما يضاهي المينوكسيديل، إكليل الجبل يحسّن دوران فروة الرأس ويقوّي بصيلات الشعر.',
      description: 'ظهر إكليل الجبل كأحد أكثر النباتات دعماً بالأدلة لصحة الشعر. أثبتت تجربة سريرية رائدة عام 2015 أن زيت إكليل الجبل فعّال مثل المينوكسيديل 2٪.',
      history: 'يُعرف بـ"عشبة التذكر" في اليونان القديمة، استُخدم طبياً لأكثر من 2000 عام.',
      benefits: [
        { icon: 'self_improvement', title: 'محفّز نمو الشعر', desc: 'تُظهر التجارب السريرية أن زيت إكليل الجبل يزيد عدد الشعر وكثافته بشكل ملحوظ.' },
        { icon: 'favorite', title: 'دوران فروة الرأس', desc: 'يحسّن الدوران الدموي الدقيق لبصيلات الشعر، مما يوصل المغذيات والأكسجين.' },
        { icon: 'healing', title: 'مثبّط DHT', desc: 'يثبّط حمض الكارنوسيك إنزيم 5-ألفا-ريداكتاز، مما يقلل تحوّل DHT.' },
      ],
      botanicalFacts: { family: 'فصيلة الشفوية', nativeRegion: 'البحر المتوسط', growthHabit: 'شجيرة خشبية معمرة', activeCompounds: 'حمض الروزمارينيك، حمض الكارنوسيك، 1,8-cineole', cultivationNotes: 'يزدهر في تربة جافة جيدة التصريف قلوية مع أشعة شمس كاملة. مقاوم للجفاف.' },
      preparation: [
        { method: 'زيت فروة الرأس', desc: 'خفِّف 3-5 قطرات من الزيت الأساسي في ملعقة كبيرة من زيت ناقل. دلّكي فروة الرأس واتركيه 30+ دقيقة.', bestFor: 'نمو الشعر وصحة فروة الرأس' },
        { method: 'شطفة الشعر', desc: 'انقع ملعقتين كبيرتين إكليل جبل مجفف في كوبين ماء ساخن لمدة 20 دقيقة. استخدم كشطفة نهائية للشعر.', bestFor: 'اللمعان وتنشيط فروة الرأس' },
      ],
      symptoms: ['تساقط الشعر', 'مشاكل فروة الرأس', 'ضعف الدورة الدموية'],
    },
    calendula: {
      name: 'القطيفة', shortDescription: 'المعيار الذهبي للعناية النباتية بالبشرة، تشفي القطيفة الجروح وتهدّئ الالتهابات وتغذي البشرة الجافة أو المتهيجة.',
      description: 'القطيفة (Calendula officinalis) من أكثر النباتات الطبية بحثاً واستخداماً في الأمراض الجلدية ورعاية الجروح.',
      history: 'تُسمى "الأقحوان" بالعربية، استُخدمت طبياً منذ مصر القديمة واليونان. استخدمها الأطباء الرومانيون لكل شيء من لسعات العقارب إلى العبادة.',
      benefits: [
        { icon: 'healing', title: 'شفاء الجروح', desc: 'تسريع تكوين النسيج الحبيبي والتظهير، مثبت سريرياً لتسريع إغلاق الجروح.' },
        { icon: 'spa', title: 'دعم حاجز البشرة', desc: 'تشكّل السكريات المتعددة طبقة واقية على البشرة مع تحفيز إنتاج الكولاجين.' },
        { icon: 'eco', title: 'مضاد للالتهابات', desc: 'تقلل التربينات الوسطاء الالتهابيين في الجلد، مهدّئةً الأكزيما والتهاب الجلد وحروق الشمس.' },
      ],
      botanicalFacts: { family: 'الفصيلة النجمية', nativeRegion: 'البحر المتوسط، غرب أوروبا', growthHabit: 'حولي أو قصير العمر', activeCompounds: 'التربينات، الفلافونويدات، السكريات المتعددة', cultivationNotes: 'سهلة الزراعة في معظم التربة مع أشعة شمس كاملة. احصد الأزهار عند انفتاحها الكامل.' },
      preparation: [
        { method: 'زيت مستخلص', desc: 'غطِّ الأزهار المجففة بزيت الزيتون لمدة 4-6 أسابيع. ضعيه مباشرةً على البشرة.', bestFor: 'شفاء البشرة والترطيب' },
        { method: 'كمادة الشاي', desc: 'اصنع شاياً قوياً، انقعي قطعة قماش، ضعيها على البشرة المصابة لمدة 15-20 دقيقة.', bestFor: 'شفاء الجروح والالتهابات' },
      ],
      symptoms: ['تهيج البشرة', 'أكزيما', 'جروح', 'جفاف البشرة'],
    },
  },
};
